version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
      NODE_ENV: test
      DATABASE_URL: postgresql://user:password@localhost:5432/database
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      NODE_ENV: test
      PORT: 3000
      DATABASE_URL: postgresql://user:password@localhost:5432/database
    depends_on:
      - db

volumes:
  postgres_data:
